const { PrismaClient } = require("@prisma/client");
const prisma = new PrismaClient();

async function main() {
  const listings = [
    {
      slug: "shoreditch-heights-a",
      name: "2B N1 A - 29 Shoreditch Heights",
      address: "Shoreditch, London",
      hostawayMapId: 1001,
      googlePlaceId: null,
    },
    {
      slug: "camden-loft-b",
      name: "Camden Loft B",
      address: "Camden, London",
      hostawayMapId: 1002,
      googlePlaceId: null,
    },
    {
      slug: "battersea-riverside-c",
      name: "Battersea Riverside C",
      address: "Battersea, London",
      hostawayMapId: 1003,
      googlePlaceId: null,
    },
  ];

  for (const l of listings) {
    await prisma.listing.upsert({
      where: { slug: l.slug },
      update: { ...l },
      create: l,
    });
  }

  // Get the created listings to use their actual IDs
  const createdListings = await prisma.listing.findMany({
    select: { id: true, slug: true }
  });
  const listingMap = {};
  createdListings.forEach(l => {
    listingMap[l.slug] = l.id;
  });

  // Add sample reviews for pagination testing
  const sampleReviews = [
    {
      id: "hostaway:rev001",
      listingId: listingMap["battersea-riverside-c"],
      source: "hostaway",
      channel: "airbnb",
      type: "guest-to-host",
      rating: 5,
      ratingRaw: 5,
      text: "Excellent guest, left the place spotless.",
      authorName: "Maria Lopez",
      submittedAt: new Date("2024-04-10"),
      approved: false,
      pinned: true,
    },
    {
      id: "hostaway:rev002",
      listingId: listingMap["camden-loft-b"],
      source: "hostaway",
      channel: "airbnb",
      type: "guest-to-host",
      rating: null,
      ratingRaw: null,
      text: "Host was responsive. The WiFi could be faster.",
      authorName: "Diego Rivera",
      submittedAt: new Date("2023-07-21"),
      approved: false,
      pinned: false,
    },
    {
      id: "hostaway:rev003",
      listingId: listingMap["camden-loft-b"],
      source: "hostaway",
      channel: "vrbo",
      type: "guest-to-host",
      rating: 4,
      ratingRaw: 4,
      text: "Nice apartment but a bit noisy on weekends.",
      authorName: "Priya Singh",
      submittedAt: new Date("2022-01-15"),
      approved: false,
      pinned: false,
    },
    {
      id: "hostaway:rev004",
      listingId: listingMap["shoreditch-heights-a"],
      source: "hostaway",
      channel: "booking",
      type: "guest-to-host",
      rating: 4.5,
      ratingRaw: 4.5,
      text: "Great location and very clean. Check-in was smooth.",
      authorName: "Alex Johnson",
      submittedAt: new Date("2021-03-02"),
      approved: false,
      pinned: false,
    },
    {
      id: "hostaway:rev005",
      listingId: listingMap["shoreditch-heights-a"],
      source: "hostaway",
      channel: "airbnb",
      type: "guest-to-host",
      rating: 5,
      ratingRaw: 5,
      text: "Shane and family are wonderful! Would definitely host again.",
      authorName: "Shane Finkelstein",
      submittedAt: new Date("2020-08-21"),
      approved: false,
      pinned: true,
    },
    {
      id: "hostaway:rev006",
      listingId: listingMap["battersea-riverside-c"],
      source: "hostaway",
      channel: "airbnb",
      type: "guest-to-host",
      rating: 4,
      ratingRaw: 4,
      text: "Beautiful riverside location with amazing views.",
      authorName: "Emma Thompson",
      submittedAt: new Date("2024-03-15"),
      approved: false,
      pinned: false,
    },
    {
      id: "hostaway:rev007",
      listingId: listingMap["camden-loft-b"],
      source: "hostaway",
      channel: "booking",
      type: "guest-to-host",
      rating: 3,
      ratingRaw: 3,
      text: "Decent stay but could use some updates to the kitchen.",
      authorName: "James Wilson",
      submittedAt: new Date("2024-02-28"),
      approved: false,
      pinned: false,
    },
    {
      id: "hostaway:rev008",
      listingId: listingMap["shoreditch-heights-a"],
      source: "hostaway",
      channel: "vrbo",
      type: "guest-to-host",
      rating: 5,
      ratingRaw: 5,
      text: "Perfect location in Shoreditch! Walking distance to everything.",
      authorName: "Sophie Chen",
      submittedAt: new Date("2024-01-20"),
      approved: false,
      pinned: true,
    },
    {
      id: "hostaway:rev009",
      listingId: listingMap["battersea-riverside-c"],
      source: "hostaway",
      channel: "airbnb",
      type: "guest-to-host",
      rating: 4.5,
      ratingRaw: 4.5,
      text: "Lovely apartment with great amenities. Highly recommend!",
      authorName: "Michael Brown",
      submittedAt: new Date("2023-12-10"),
      approved: false,
      pinned: false,
    },
    {
      id: "hostaway:rev010",
      listingId: listingMap["camden-loft-b"],
      source: "hostaway",
      channel: "booking",
      type: "guest-to-host",
      rating: 2,
      ratingRaw: 2,
      text: "Had some issues with heating during winter stay.",
      authorName: "Lisa Anderson",
      submittedAt: new Date("2023-11-05"),
      approved: false,
      pinned: false,
    },
    {
      id: "hostaway:rev011",
      listingId: listingMap["shoreditch-heights-a"],
      source: "hostaway",
      channel: "airbnb",
      type: "guest-to-host",
      rating: 5,
      ratingRaw: 5,
      text: "Amazing location! Perfect for exploring East London. Host was very accommodating.",
      authorName: "Rachel Green",
      submittedAt: new Date("2024-05-15"),
      approved: false,
      pinned: true,
    },
    {
      id: "hostaway:rev012",
      listingId: listingMap["battersea-riverside-c"],
      source: "hostaway",
      channel: "vrbo",
      type: "guest-to-host",
      rating: 4.5,
      ratingRaw: 4.5,
      text: "Beautiful views of the Thames. The apartment was spotless and well-equipped.",
      authorName: "David Kim",
      submittedAt: new Date("2024-04-28"),
      approved: false,
      pinned: false,
    },
    {
      id: "hostaway:rev013",
      listingId: listingMap["camden-loft-b"],
      source: "hostaway",
      channel: "booking",
      type: "guest-to-host",
      rating: 4,
      ratingRaw: 4,
      text: "Great loft space with high ceilings. Close to Camden Market and tube station.",
      authorName: "Sarah Williams",
      submittedAt: new Date("2024-03-20"),
      approved: false,
      pinned: false,
    },
    {
      id: "hostaway:rev014",
      listingId: listingMap["shoreditch-heights-a"],
      source: "hostaway",
      channel: "airbnb",
      type: "guest-to-host",
      rating: 3.5,
      ratingRaw: 3.5,
      text: "Nice place but could use better soundproofing. Street can be noisy at night.",
      authorName: "Tom Bradley",
      submittedAt: new Date("2024-02-14"),
      approved: false,
      pinned: false,
    },
    {
      id: "hostaway:rev015",
      listingId: listingMap["battersea-riverside-c"],
      source: "hostaway",
      channel: "airbnb",
      type: "guest-to-host",
      rating: 5,
      ratingRaw: 5,
      text: "Exceptional stay! The riverside location is unbeatable. Will definitely return.",
      authorName: "Jennifer Martinez",
      submittedAt: new Date("2024-01-30"),
      approved: false,
      pinned: true,
    },
    {
      id: "hostaway:rev016",
      listingId: listingMap["camden-loft-b"],
      source: "hostaway",
      channel: "vrbo",
      type: "guest-to-host",
      rating: 4.5,
      ratingRaw: 4.5,
      text: "Loved the industrial design and spacious layout. Perfect for a weekend getaway.",
      authorName: "Mark Thompson",
      submittedAt: new Date("2023-12-18"),
      approved: false,
      pinned: false,
    },
    {
      id: "hostaway:rev017",
      listingId: listingMap["shoreditch-heights-a"],
      source: "hostaway",
      channel: "booking",
      type: "guest-to-host",
      rating: 4,
      ratingRaw: 4,
      text: "Good location for business travel. Easy access to the City and Canary Wharf.",
      authorName: "Anna Rodriguez",
      submittedAt: new Date("2023-11-22"),
      approved: false,
      pinned: false,
    },
    {
      id: "hostaway:rev018",
      listingId: listingMap["battersea-riverside-c"],
      source: "hostaway",
      channel: "booking",
      type: "guest-to-host",
      rating: 3,
      ratingRaw: 3,
      text: "Nice apartment but had issues with the WiFi during my stay.",
      authorName: "Chris Evans",
      submittedAt: new Date("2023-10-10"),
      approved: false,
      pinned: false,
    },
    {
      id: "hostaway:rev019",
      listingId: listingMap["camden-loft-b"],
      source: "hostaway",
      channel: "airbnb",
      type: "guest-to-host",
      rating: 5,
      ratingRaw: 5,
      text: "Outstanding host and beautiful space! Everything was perfect from check-in to check-out.",
      authorName: "Michelle Lee",
      submittedAt: new Date("2023-09-25"),
      approved: false,
      pinned: true,
    },
    {
      id: "hostaway:rev020",
      listingId: listingMap["shoreditch-heights-a"],
      source: "hostaway",
      channel: "vrbo",
      type: "guest-to-host",
      rating: 4.5,
      ratingRaw: 4.5,
      text: "Fantastic location in the heart of Shoreditch. Walking distance to great restaurants and bars.",
      authorName: "Robert Davis",
      submittedAt: new Date("2023-08-15"),
      approved: false,
      pinned: false,
    },
  ];

  for (const review of sampleReviews) {
    await prisma.review.upsert({
      where: { id: review.id },
      update: review,
      create: review,
    });
  }

  console.log("Seeded listings:", listings.map(l => l.slug));
  console.log("Seeded reviews:", sampleReviews.length);
}

main().catch((e) => {
  console.error(e);
  process.exit(1);
}).finally(async () => {
  await prisma.$disconnect();
});
